{% set title = "Duplicates" %}
{%- macro metaSection(version, Primary, Secondary, breadcrumbs, duplicateId, distance=null) %}
    {% set cssModifier = version == "primary" ? "--primary" : "--secondary" %}
    {% set areaCss = Primary.Area() > Secondary.Area() ? "fw-bold text-success" : "" %}
    {% set fileSizeCss = Primary.filesize > Secondary.filesize ? "fw-bold text-success" : "" %}
    {% set idCss = Primary.id < Secondary.id ? "fw-bold text-success" : "" %}
    <div class="duplicate__area{{ cssModifier }} {{ areaCss}}">
        {% if Primary.Area() > Secondary.Area() %}
            {{ icon("bi bi-arrow-up-circle-fill text-success") }}
        {% endif %}
        {{ Primary.width }} &times; {{ Primary.height}}
    </div>
    <div class="duplicate__size{{ cssModifier }} {{ fileSizeCss }}">
        {% if Primary.filesize > Secondary.filesize %}
            {{ icon("bi bi-arrow-up-circle-fill text-success") }}
        {% endif %}
        {{ filesize(Primary.filesize) }}
    </div>
    <div class="duplicate__format{{ cssModifier }}">
        {{ Primary.mime_type }}
    </div>
    <div class="duplicate__id{{ cssModifier }} {{ idCss }}">
        #{{ Primary.id }}
    </div>
    {% if version == "primary" %}
        <div class="duplicate__distance-label">
            Distance:
        </div>
    {% else %}
        <div class="duplicate__distance">
            {{ distance }}
        </div>
    {% endif %}
    <div class="duplicate__breadcrumb{{ cssModifier }}">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0">
                {% for album in breadcrumbs[Primary.id] %}
                    <li class="breadcrumb-item">
                        <a href="{{ album(album.id) }}" target="_new">{{ album.name }}</a>
                    </li>
                {% endfor %}
            </ol>
        </nav>
    </div>
    <div class="duplicate__take{{ cssModifier }}">
        <button class="btn btn-success js-take" data-duplicate-id="{{ duplicateId }}" data-take="{{ version }}">
            Take
        </button>
    </div>
    <div class="duplicate__orig{{ cssModifier }}">
        <a href="{{ photo(Primary.path) }}" class="btn btn-ghost-secondary" target="_blank">
            Original {{ icon("bi-arrow-up-right")}}
        </a>
    </div>
{%- endmacro %}

<div class="overflow-auto">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="d-flex justify-content-between align-items-center">
                    <h1>
                        Duplicates {% if duplicates|length > 0 %}<small class="text-body-secondary">(<span id="duplicates-count">{{ duplicates|length }}</span>){% endif %}
                    </h1>
                    <div class="d-flex gap-2 align-items-center">
                        <form method="post" action="{{ url('duplicates/find') }}" id="find-form">
                            <div class="input-group">
                                <span class="input-group-text">Distance:</span>
                                <input type="text" name="distance" class="form-control" value="{{ distance }}" style="width:50px;" />
                                <button type="submit" class="btn btn-secondary">Find</button>
                            </div>
                        </form>
                        {% if ignoredDuplicatesExist %}
                            <form method="post" action="{{ url('duplicates/clear') }}" id="clear-form">
                                <button type="submit" class="btn btn-secondary">Clear</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
                {% for duplicate in duplicates %}
                    <div class="duplicate" id="duplicate-{{ duplicate.id }}">
                        <div class="duplicate__img-container--primary zoom__container">
                            <img src = "{{ photo(duplicate.Primary.display_path) }}"
                                class="duplicate__img zoom__img"
                                data-zoom-src="{{ photo(duplicate.Primary.path) }}"
                                alt="{{ duplicate.Primary.id }}" />
                        </div>
                        {{ metaSection("primary", duplicate.Primary, duplicate.Secondary, breadcrumbs, duplicate.id) }}
                        {{ metaSection("secondary", duplicate.Secondary, duplicate.Primary, breadcrumbs, duplicate.id, duplicate.distance) }}
                        <div class="duplicate__img-container--secondary zoom__container">
                            <img src = "{{ photo(duplicate.Secondary.display_path) }}"
                                class="duplicate__img zoom__img"
                                data-zoom-src="{{ photo(duplicate.Secondary.path) }}"
                                alt="{{ duplicate.Secondary.id }}" />
                        </div>
                        <button class="btn btn-secondary duplicate__ignore js-ignore" data-duplicate-id="{{ duplicate.id}}">Ignore</button>
                    </div>
                    {% else %}
                        <p class="alert alert-light">
                            No duplicates have been found.
                        </p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<script defer src = "{{ url('/public/js/zoom.js') }}" type="module"></script>