<div class="contenders">
    {% for photo in photos %}
        <div class="contender" data-id="{{ photo.id }}">
            <img src = "{{ photo(photo.display_path) }}" />
            <div class="contender__meta">
                <div>
                    <a href="{{ album(photo.firstAlbum().id) }}" class="btn bg-frosted btn-outline-secondary" target="_blank">{{ photo.firstAlbum().name }} {{ icon('bi-arrow-up-right') }}</a>
                    <a href="{{ photo(photo.path) }}" class="btn bg-frosted btn-outline-secondary" target="_blank">Original {{ icon('bi-arrow-up-right') }}</a>
                </div>
                <div class="d-flex gap-2">
                    <span class="badge bg-frosted rounded-pill text-dark">
                        #{{ photo.id }}
                    </span>
                    <span class="badge bg-frosted rounded-pill text-dark">
                        {{ icon("bi-bar-chart") }} {{ photo.battles }}
                    </span>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
<div class = "modal" id="stats-modal">
    <div class = "modal-dialog modal-dialog-scrollable modal-fullscreen">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Battle stats</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="stats-body">
                Nothing
            </div>
        </div>
    </div>
</div>
<script type="module" src = "{{ url('/public/js/battle.js') }}"></script>
<form method = "post" action = "battle" id="form">
    <input type="hidden" name="winnerId" id="winner-id-field" />
    <input type="hidden" name="loserId" id = "loser-id-field" />
</form>