<div class="contenders">
    <div class="battle__mask d-none"></div>
    {% for photo in photos %}
        <div class="contender" data-contender-id="{{ photo.id }}">
            <div class="contender__img-wrapper zoom__container">
                <img class="js-contender-img zoom__img zoom__img--no-zoom" src = "{{ photo(photo.display_path) }}" data-zoom-src = "{{ photo(photo.path) }}"/>
            </div>
            <div class="contender__meta">
                {% if breadcrumbs[photo.id] is defined %}
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb mb-0">
                            {% for album in breadcrumbs[photo.id] %}
                                <li class="breadcrumb-item">
                                    <a href="{{ album(album.id) }}" target="_new">{{ album.name }}</a>
                                </li>
                            {% endfor %}
                        </ol>
                    </nav>
                {% endif %}
                <div class="d-flex gap-2">
                    <span>
                        #{{ photo.id }}
                    </span>
                    <span>
                        {{ icon("bi-bar-chart") }} {{ photo.battles }}
                    </span>
                </div>
                <a href="{{ photo(photo.path) }}" class="btn bg-frosted btn-outline-secondary" target="_blank">Original {{ icon('bi-arrow-up-right') }}</a>
            </div>
        </div>
    {% endfor %}
</div>
<div class = "modal" id="stats-modal">
    <div class = "modal-dialog modal-dialog-scrollable modal-fullscreen">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Battle stats</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="stats-body">
                Nothing
            </div>
        </div>
    </div>
</div>
<form method = "post" action = "battle" id="form">
    <input type="hidden" name="winnerId" id="winner-id-field" />
    <input type="hidden" name="loserId" id = "loser-id-field" />
</form>