<h5>
    Distribution
</h5>
<div class = "battle-dist mb-3">
    <?php foreach ($distribution as $battles => $count) { ?>
        <?php
            $percentage = ceil($count/max($distributionMax,1) * 100);
        ?>
        <div class="battle-dist__col" data-bs-toggle="tooltip" title="<?= $count ?>">
            <div class="battle-dist__bar-container">
                <div class="battle-dist__bar <?php if ($percentage == 0) { ?>visually-hidden<?php } ?>" style="--percentage: <?= $percentage ?>%"></div>
            </div>
            <div class="battle-dist__label"><?= $battles ?></div>
        </div>
    <?php } ?>
</div>
<h5>
    Popular photos
</h5>
<div class = "battle__ranking mb-3">
    <?php foreach ($popularPhotos as $photo) { ?>
        <div class="battle__rankee" style="--percentage:<?= $photo->wins / $photo->battles * 100 ?>%">
            <div class="battle__rankee-rate"><?= $photo->wins ?>/<?= $photo->battles ?></div>
            <img class="battle__rankee-img"
                src = "<?= $this->viewHelper->photoUrl($photo->thumb_path) ?>"
                data-bs-toggle="popover"
                data-bs-content="<img src = '<?= $this->viewHelper->photoUrl($photo->display_path) ?>' class='mw-100'>"
                data-bs-html="true"
                data-bs-trigger="hover"
                data-bs-custom-class="battle__stat-popover"
            >
        </div>
    <?php } ?>
</div>
<h5>
    Popular albums
</h5>
<div class = "battle__ranking mb-3">
    <?php foreach ($popularAlbums as $album) { ?>
        <div class="battle__rankee" style="--percentage:<?= $album->success * 100 ?>%">
            <div class = "battle__rankee-rate"><?= $album->photoWins ?>/ <?= $album->photoBattles ?></div>
            <img class="battle__rankee-img"
                src = "<?= $this->viewHelper->photoUrl($album->thumb_path) ?>"
                data-bs-toggle="popover"
                data-bs-content="<img src = '<?= $this->viewHelper->photoUrl($album->thumb_path) ?>' class='mw-100'><div class='text-center fw-bold fs-5 mt-3'><?= $album->name ?></div>"
                data-bs-html="true"
                data-bs-trigger="hover"
                data-bs-custom-class="battle__stat-popover"
            >
        </div>
    <?php } ?>
</div>