<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            <?php if (isset($title)) { ?><?= $title ?> &lt; <?php } ?>Photolib
        </title>
        <link rel = "stylesheet" type="text/css" href="<?= $this->url->get('/public/css/style.css') ?>">
        <script defer src="https://cdn.jsdelivr.net/npm/sortablejs@1.15.0/Sortable.min.js"></script>
    </head>
    <body>
        <div class="upload-progress" :class="files.length > 0 && 'upload-progress__show'" x-data="uploadProgress">
            <div class="upload-progress__total progress" x-ref="total">
                <div class="progress-bar" :style="{width: filesDonePercentage + '%'}"></div>
            </div>
        </div>
        <div class = "app">
            <div class="navbar">
                <div class="d-flex">
                    <div class="navbar-brand">
                        <a class="navbar-icon" href = "<?= $this->viewHelper->albumUrl($this->config->rootAlbumId) ?>">PL</a>
                        <?php if (isset($title)) { ?>
                            <?= $title ?>
                        <?php } ?>
                    </div>
                    <?php if (isset($Album)) { ?>
                        <div class="d-inline-flex align-items-center gap-1" x-data="{}" :class="$store.sorting && 'invisible'">
                            <?php if (!$Album->isRootAlbum()) { ?>
                                <div class="dropdown dropdown--no-caret">
                                    <button class="btn btn-appear-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                        <?= $this->viewHelper->icon('bi-gear-fill') ?>
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a class="dropdown-item" href="#" x-data="albumRename" @click="start('<?= $this->escaper->js($Album->name) ?>', <?= $Album->id ?> )">
                                                <?= $this->viewHelper->icon('bi-input-cursor-text me-2') ?>Rename
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" href="#" x-data="albumMove" @click="start()">
                                                <?= $this->viewHelper->icon('bi-folder-symlink me-2') ?>Move
                                            </a>
                                        </li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li>
                                            <?php if ($this->length($subAlbums) > 0 || $Album->hasPhotos()) { ?>
                                                <small class="form-text d-block ps-3 lh-sm text-danger">
                                                    This album cannot be deleted because it contains photos and/or albums.
                                                </small>
                                            <?php } else { ?>
                                                <a class="dropdown-item text-danger" href="#" x-data="albumDelete" @click="deleteAlbum()">
                                                    <?= $this->viewHelper->icon('bi-trash-fill me-2') ?>Delete
                                                </a>
                                            <?php } ?>
                                        </li>
                                    </ul>
                                </div>
                            <?php } ?>
                            <button class="btn btn-appear-secondary" data-bs-toggle="modal" data-bs-target="#new-album-modal">
                                <?= $this->viewHelper->icon('bi-folder-plus') ?>
                            </button>
                        </div>
                    <?php } ?>
                </div>
                <?php if (isset($Album)) { ?>
                    <div class="btn-toolbar gap-3" role="toolbar" aria-label="Album-wide tools">
                        <div class="d-flex gap-1" x-data="gridSize">
                            <div class="btn btn-appear-secondary btn-icon" :class="size == 'sm' && 'active'" @click="setSize('sm')">
                                <?= $this->viewHelper->icon('bi-grid-3x3-gap') ?>
                            </div>
                            <div class="btn btn-appear-secondary btn-icon" :class="size == 'lg' && 'active'" @click="setSize('lg')">
                                <?= $this->viewHelper->icon('bi-grid') ?>
                            </div>
                        </div>
                        <div class="d-flex gap-1" x-data="gridRatio">
                            <div class="btn btn-appear-secondary btn-icon" :class="ratio == 'square' && 'active'" @click="setRatio('square')">
                                <?= $this->viewHelper->icon('bi-aspect-ratio') ?>
                            </div>
                            <div class="btn btn-appear-secondary btn-icon"  :class="ratio == 'natural' && 'active'" @click="setRatio('natural')">
                                <?= $this->viewHelper->icon('bi-square') ?>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                <?php if ($this->router->getControllerName() != 'battle') { ?>
                    <a href ="<?= $this->url->get('/battle') ?>" class="btn btn-icon btn-outline-secondary">
                        <?= $this->viewHelper->icon('bi-bar-chart') ?>
                    </a>
                <?php } else { ?>
                    <a href="#" class="btn btn-outline-secondary" id="battle-stats">
                        Stats
                    </a>
                <?php } ?>
            </div>
            <?= $this->getContent(); ?>
        </div>
        <script type="text/javascript">
            window.webRootPath = "<?= $this->config->dirs->web->root ?>";
            window.rootAlbumId = <?= $this->config->rootAlbumId ?>;
        </script>
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
        <script src = "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src = "<?= $this->url->get('/public/js/site.js') ?>" type="module"></script>
    </body>
</html>