<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            <?php if (isset($title)) { ?><?= $title ?> &lt; <?php } ?>Photolib
        </title>
        <link rel = "stylesheet" type="text/css" href="<?= $this->url->get('/public/css/style.css') ?>" />
    </head>
    <body>
        <div class = "app">
            <div class="navbar">
                <div class="navbar-brand">
                    <a class="navbar-icon" href = "<?= $this->viewHelper->albumUrl(1) ?>">PL</a>
                    <?php if (isset($title)) { ?>
                        <?= $title ?>
                    <?php } ?>
                </div>
                <?php if (isset($Album)) { ?>
                    <div class="btn-toolbar gap-2" role="toolbar" aria-label="Album-wide tools">
                        <div class="btn-group" x-data="gridSize">
                            <div class="btn btn-outline-secondary" :class="size == 'sm' && 'active'" @click="setSize('sm')">
                                <?= $this->viewHelper->icon('bi-grid-3x3-gap') ?>
                            </div>
                            <div class="btn btn-outline-secondary" :class="size == 'lg' && 'active'" @click="setSize('lg')">
                                <?= $this->viewHelper->icon('bi-grid') ?>
                            </div>
                        </div>
                        <div class="btn-group" x-data="gridRatio">
                            <div class="btn btn-outline-secondary" :class="ratio == 'square' && 'active'" @click="setRatio('square')">
                                <?= $this->viewHelper->icon('bi-aspect-ratio') ?>
                            </div>
                            <div class="btn btn-outline-secondary"  :class="ratio == 'natural' && 'active'" @click="setRatio('natural')">
                                <?= $this->viewHelper->icon('bi-square') ?>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                <a href ="<?= $this->url->get('/battle') ?>" class="btn btn-outline-secondary">
                    <?= $this->viewHelper->icon('bi-bar-chart') ?>
                </a>
            </div>
            <?= $this->getContent(); ?>
        </div>
        <script src = "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src = "<?= $this->url->get('/public/js/site.js') ?>" type="module"></script>
    </body>
</html>