<div class="modal fade chooser__modal" tabindex="-1" aria-label="Album chooser" x-data="albumChooser({{ Album.id }})">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class = "modal-header flex-column align-items-start" :class = "{'border-bottom-0': albums.length == 0}">
                <template x-if="Album != null">
                    <h5 class = "modal-title d-flex w-100 mb-2">
                        <template x-if="Album.id != window.rootAlbumId">
                            <a @click="loadAlbum(Parent.id)" href = "#">
                                {{ icon("bi-chevron-left") }} <span x-text="Album.name"></span>
                            </a>
                        </template>
                        <template x-if="Album.id == window.rootAlbumId">
                            <span x-text="Album.name"></span>
                        </template>
                        <button type = "button" class = "btn btn-sm btn-ghost-primary ms-2" @click="choose(Album)">Choose</button>
                        <button @click = "cancel()" type="button" class="btn-close" aria-label="Close"></button>
                    </h5>
                </template>
                <div class = "input-group" x-data="filter('.chooser__list .chooser__item')">
                    <input type = "text" class = "form-control filter__input" x-model="searchTerms" required placeholder = "Filter albums" autocomplete = "off">
                    <button class = "btn btn-ghost-secondary filter__button" @click="clear()">
                        {{ icon("bi-x-lg") }}
                    </button>
                </div>
            </div>
            <div class="modal-body p-0">
                <template x-if="albums.length > 0">
                    <ul class = "list-group list-group-flush chooser__list">
                        <template x-for = "subalbum in albums" :key="subalbum.id">
                            <li class = "list-group-item chooser__item" :data-filter-on="subalbum.name">
                                <template x-if="subalbum.subAlbumCount > 0">
                                    <a href = "#" class = "chooser__title" @click="loadAlbum(subalbum.id)">
                                        <span x-text="subalbum.name"></span>{{ icon("bi-chevron-right") }}</a>
                                    </a>
                                </template>
                                <template x-if="subalbum.subAlbumCount == 0">
                                    <span x-text="subalbum.name" class = "chooser__title"></span>
                                </template>
                                <button type = "button" class = "btn btn-sm btn-ghost-primary" @click="choose(subalbum)">Choose</button>
                            </li>
                        </template>
                    </ul>
                </template>
            </div>
        </div>
    </div>
</div>