<div class="modal modal-xl fade chooser__modal" tabindex="-1" aria-label="Album chooser" x-data="photoChooser()">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class = "modal-header">
                <h5 class="modal-title">
                    Choose replacement photo
                </h5>
                <button @click = "cancel()" type="button" class="btn-close" aria-label="Close"></button>
            </div>
            <div class="modal-body p-0">
                <div class="photochooser__grid">
                    {% for photo in photos %}
                        <button type="button" class="photochooser__tile" @click="choose({{photo.id}})">
                            <img src="{{ photo(photo.thumb_path) }}" style="max-width:200px;max-height:200px;"/><br />
                            {{ photo.width }} &times; {{ photo.height }}<br />
                            {{ filesize(photo.filesize) }}<br />
                            {{ formatDatetime(photo.date_uploaded) }}
                        </button>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>