<div class="album">
    <div class="album__sidebar">
        <div class="p-2 pt-0">
            <div class="input-group" x-data="filter('.sidebar__list-group .sidebar__list-item, .grid__item:has(.grid__album)', '{{ q|escape_js }}')">
                {# required is needed to be able to target with css.  See _sidebar.scss #}
                <input type="text" class="form-control filter__input" required x-model="searchTerms" autofocus>
                <button class="btn btn-outline-input btn-icon filter__button" @click="clear()">
                    {{ icon("bi-x-lg") }}
                </button>
            </div>
        </div>
        <div class = "list-group list-group-flush list-group--sm sidebar__list-group">
            {% for album in menuAlbums %}
                <a class = "list-group-item list-group-item-action {% if Album.id == album.id %}active{% endif %} sidebar__list-item d-flex justify-content-between align-items-center"
                   data-filter-on = "{{ album.name|escape_attr }}"
                   href="{{ album(album.id) }}">
                    {{ album.name }}
                    {% if album.subAlbumCount != 0 %}
                        <span class="badge rounded-pill border-circle text-bg-secondary">{{ album.subAlbumCount }}</span>
                    {% endif %}
                </a>
            {% endfor %}
        </div>
    </div>
    <div class="album__main">
        <div class = "album__header">
            {#
                Breadcrumbs
            #}
            <nav aria-label="breadcrumb" class="album__breadcrumb">
                <ol class="breadcrumb">
                    {% for crumb in breadcrumbs %}
                        {% set active = loop.last ? "active" : "" %}
                        <li class="breadcrumb-item {{ active }}">
                            {% if !loop.last %}
                                <a href="{{ album(crumb.id) }}">
                            {% endif %}
                            {% if loop.first %}{{ icon("bi-house-fill me-1") }}{% endif %}{{ crumb.name }}
                            {% if loop.last %}
                                <div class = "breadcrumb__breakdown">
                                    {{ partial("album/partials/breakdown",["albums": subAlbums|length, "photos": Album.photos|length]) }}
                                </div>
                            {% endif %}
                            {% if !loop.last %}
                                </a>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ol>
            </nav>

            <div class="d-flex gap-1">
                <div class="d-flex gap-1" x-data="reorder">
                    <template x-if="!$store.sorting && $store.albumOrder.current == 'manual'">
                        <template x-if="$store.albumOrder.current == 'manual'">
                            <button class="btn btn-ghost-secondary btn-icon" @click="startReorder()">
                                {{ icon("bi-arrow-left-right") }}
                            </button>
                        </template>
                    </template>
                    <template x-if="!$store.sorting && $store.albumOrder.current != 'manual'">
                        <button class="btn btn-ghost-secondary btn-icon text-danger" title="Photos cannot be manually re-ordered unless they are sorted by 'Manual'">
                            {{ icon("bi-arrow-left-right") }}
                        </button>
                    </template>
                    <template x-if="$store.sorting">
                        <button class="btn btn-success btn-icon" @click="saveOrder()">
                            {{ icon("bi-check") }}
                        </button>
                    </template>
                    <template x-if="$store.sorting">
                        <button class="btn btn-danger btn-icon" @click="cancelOrder()">
                            {{ icon("bi-x") }}
                        </button>
                    </template>
                </div>
                <div x-data="order">
                    <template x-if="!$store.sorting">
                        <div class="dropdown">
                            <button class="btn btn-ghost-secondary dropdown-toggle" 
                                    type="buton" 
                                    data-bs-toggle="dropdown" 
                                    aria-expanded="false"
                                    x-text="'Order: ' + orderTypes[$store.albumOrder.current].label"
                                    >
                            </button>
                            <ul class="dropdown-menu">
                                <template  x-for="(entry, key) in orderTypes" :key="key">
                                    <li>
                                        <a href="#" class="dropdown-item" @click="order(key)">
                                            <i :class="entry.icon"></i>
                                            <span x-text="entry.label"></span>
                                        </a>
                                    </li>
                                </template>
                            </ul>
                        </div>
                    </template>
                </div>
                <div x-data="slideshow" x-show="!$store.sorting">
                    <button class="btn btn-ghost-secondary btn-icon" @click="showDialog = true">
                        {{ icon("bi-collection-play")}}
                    </button>
                    <template x-if="show">
                        <div id="slideshow" class="mask" tabindex="0" x-ref="mask" @click="end()" @keydown.escape="end()">
                            <div class="slideshow__loading" x-show="loading">Loading&hellip;</div>
                            <div class="slideshow__slide" :class="activeSlide == 0 ? 'active' : ''">
                                <img class="slideshow__img" :src="src[0]" @click.stop="fastForward()"/>
                            </div>
                            <div class="slideshow__slide" :class="activeSlide == 1 ? 'active' : ''">
                                <img class="slideshow__img" :src="src[1]" @click.stop="fastForward()"/>
                            </div>
                        </div>
                    </template>
                    <dialog x-ref="dialog" class="slideshow__dialog" @close="showDialog = false">
                        {% if Album.photos|length > 0 %}
                            <p>
                                Include photos from child albums, or just this album?
                            </p>
                            <button type="button" class="btn btn-secondary" @click="start(true)">With child albums</button>
                            <button type="button" class="btn btn-secondary" @click="start(false)">Just this album</button>
                        {% else %}
                            <p>
                                Slideshow will consist of photos from child albums, as this album has no photos
                            </p>
                            <button type="button" class="btn btn-secondary" @click="start(true)">Ok</button>
                        {% endif %}
                    </dialog>
                </div>
                {#
                    Uploading
                #}
                {% if !Album.isRootAlbum() %}
                <div x-data="upload">
                    <div class = "d-flex gap-1" :class="$store.sorting && 'invisible'">
                        <button class="btn btn-ghost-secondary btn-icon" @click="startDownload()">
                            {{ icon("bi-cloud-arrow-down") }}
                        </button>
                        <span>
                            <button class="btn btn-ghost-secondary btn-icon" @click="filesChoose()">
                                {{ icon("bi-upload") }}
                            </button>
                            <div class="d-none">
                                <input type="file" x-ref="fileInput" multiple @change="filesChosen($event)"/>
                            </div>
                        </span>
                        <div class = "drop-target">
                            <div class = "drop-target__target">
                                Drop files
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>

        {#
            Grid
        #}
        <div class="album__grid-container">
            <div class="album__grid">
                {#
                    Albums
                #}
                {% for subAlbum in subAlbums %}
                    <div class="grid__item {% if Featured IS NOT null AND subAlbum.photo_id == Featured.id %}grid__item--featured {% endif %}" id="album-{{ subAlbum.id}}" data-filter-on="{{ subAlbum.name }}">
                        {% if subAlbum.hasFeatured() %}
                            <div class="grid__photo-btn grid__tools">
                                <div class="dropdown dropdown--no-caret">
                                    <button class="btn btn-grid dropdown-toggle" id="tools-{{ subAlbum.id }}" data-bs-toggle="dropdown" aria-expanded="false">
                                        {{ icon("bi-three-dots-vertical") }}
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledBy="tools-{{ subAlbum.id }}">
                                        <li x-data="albumFeature('album-' + {{ subAlbum.id }}, {{ Album.id }})">
                                            <a class="dropdown-item" href="#" @click="feature({{ subAlbum.Featured.id}})">Feature</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        {% endif %}
                        <a class="grid__album" href="{{ album(subAlbum.id) }}">
                            {% if subAlbum.hasFeatured() %}
                                <img class="grid__album-image" src = "{{ photo(subAlbum.Featured.thumb_path) }}" loading="lazy" alt="{{ subAlbum.name }}"/>
                            {% else %}
                                {# Not sure where this icon came from #}
                                <svg class="grid__album-image" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="0.5" stroke-linecap="round" stroke-linejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                            {% endif %}
                            <div class="grid__caption">
                                {{ subAlbum.name }}
                                <span class="ms-2">
                                    {{ partial("album/partials/breakdown",["albums": subAlbum.subAlbumCount, "photos": 0]) }}
                                </span>
                            </div>
                        </a>
                    </div>
                {% endfor %}

                {#
                    Photos
                #}
                {% for index, photo in Album.photos %}
                    {% include "album/partials/photo.phtml" %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div class = "lightbox mask"
    x-data="lightbox"
    x-on:lightboxable-clicked.window="box($event.detail)"
    :class="show ? 'lightbox--show' : ''"
    [x-cloak]>
    <div class="lightbox__current zoom__container" @click="show=false" x-ref="current">
        <img class="lightbox__img zoom__img" :src="photo?.dataset.src ?? ''" :data-zoom-src="photo?.dataset.zoomSrc"/>
    </div>
    <div class = "lightbox__previous" @click="box(previous)" x-show="previous != null">
        <img class="lightbox__img--previous" :src="previous?.dataset.src"/>
    </div>
    <div class = "lightbox__next" @click="box(next)" x-show="next != null">
        <img class="lightbox__img--next" :src="next?.dataset.src"/>
    </div>
    <div  class = "lightbox__details">
        <span class = "lightbox__detail" x-text="`${photo?.dataset.width} x ${photo?.dataset.height}`"></span>
        <span class = "lightbox__detail" x-text="photo?.dataset.filesize"></span>
        <a class = "lightbox__detail btn btn-sm btn-outline-light" :href = "photo?.dataset.originalSrc" target = "_blank">Original {{ icon("bi-box-arrow-up-right") }}</a>
    </div>
</div>
{{ partial("album/partials/album-new") }}
{{ partial("album/partials/album-chooser") }}
{{ partial("album/partials/photo-chooser", ['photos': Album.photos]) }}
<script type="text/javascript">
    window.albumId = {{ Album.id }};
    window.parentAlbumId = {{ Album.album_id|default(0) }};
    window.slideshowDuration = {{ config.slideshow.duration }};
</script>
<style type="text/css">
    :root{
        --slideshow-slide-duration: {{config.slideshow.duration}}ms;
    }
</style>