<div class="album">
    <div class="album__sidebar">
            <div class="p-2 pt-0">
                <div class="input-group">
                    {# required is needed to be able to target with css.  See _sidebar.scss #}
                    <input type="text" class="form-control" required id="sidebar-search"/>
                    <button class="btn btn-outline-input lh-1" id="sidebar-search-clear">
                        {{ icon("bi-x-lg") }}
                    </button>
                </div>
            </div>
        <div class = "list-group list-group-flush list-group--sm sidebar__list-group">
            {% for album in menuAlbums %}
                <a class = "list-group-item list-group-item-action {% if Album.id == album.id %}active{% endif %} sidebar__list-item" 
                   data-album-name = "{{ album.name|escape_attr }}"
                   href="{{ album(album.id) }}">
                    {{ album.name }}
                </a>
            {% endfor %}
        </div>
    </div>
    <div class="album__main">
        {#
            Breadcrumbs
        #}
        <nav aria-label="breadcrumb" class="album__breadcrumb">
            <ol class="breadcrumb">
                {% for crumb in breadcrumbs %}
                    {% set active = loop.last ? "active" : "" %}
                    <li class="breadcrumb-item {{ active }}">
                        {% if !loop.last %}
                            <a href="{{ album(crumb.id) }}">
                        {% endif %}
                        {% if loop.first %}{{ icon("bi-house-fill me-1") }}{% endif %}{{ crumb.name }}
                        {% if !loop.last %}
                            </a>
                        {% endif %}
                    </li>
                {% endfor %}
            </ol>
        </nav>

        {#
            Grid
        #}
        <div class="album__grid-container">
            <div class="album__grid">
                {#
                    Albums
                #}
                {% for album in Album.albums %}
                    <div class="grid__item {% if Album.isFeatured(album.Featured) %}grid__item--featured {% endif %}">
                        <a class="grid__album" href="{{ album(album.id) }}">
                            {% if album.Featured != null %}
                                <img src = "{{ photo(album.Featured.thumb_path) }}" loading="lazy" />
                            {% endif %}
                            <div class="grid__caption">
                                {{ album.name }}
                            </div>
                        </a>
                    </div>
                {% endfor %}

                {#
                    Photos
                #}
                {% for photo in Album.photos %}
                    <div class="grid__item {% if Album.IsFeatured(photo) %}grid__item--featured{% endif %}">
                        <div class="grid__photo">
                            <button class="btn btn-grid grid__photo-btn grid__info" 
                                data-bs-toggle="popover"
                                data-bs-html="true"
                                data-width="{{ photo.width }}"
                                data-height="{{ photo.height }}"
                                data-filesize="{{ filesize(photo.filesize) }}"
                                data-battles="{{ photo.battles }}"
                                data-win-percentage="{{ photo.winPercentage() }}"
                                data-content="Content failed to load."
                            >
                                {{ icon("bi-info-circle") }}
                            </button>
                            <button class="btn btn-grid grid__photo-btn grid__tools">
                                {{ icon("bi-three-dots-vertical") }}
                            </button>
                            <img class="lightboxable"
                                 loading="lazy"
                                 src = "{{ photo(photo.thumb_path) }}" 
                                 data-src = "{{ photo(photo.display_path) }}" 
                                 data-width = "{{ photo.width }}"
                                 data-height = "{{ photo.height }}"
                                 data-filesize = "{{ photo.filesize }}"
                                 data-original-src = "{{ photo.path }}"
                            />
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div class = "lightbox" 
    x-data="lightbox" 
    x-on:lightboxable-clicked.window="box($event.detail)" 
    :class="show ? 'lightbox--show' : ''" 
    [x-cloak]>
    <div class="lightbox__current" @click="show=false">
        <img class="lightbox__img" :src="photo?.dataset.src ?? ''"/>
    </div>
    <div class = "lightbox__previous" @click="box(previous)" x-show="previous != null">
        <img class="lightbox__img--previous" :src="previous?.dataset.src"/>
    </div>
    <div class = "lightbox__next" @click="box(next)" x-show="next != null">
        <img class="lightbox__img--next" :src="next?.dataset.src"/>
    </div>
    <div  class = "lightbox__details">
        <span class = "lightbox__detail" x-text="`${photo?.dataset.width} x ${photo?.dataset.height}`"></span>
        <span class = "lightbox__detail" x-text="`${Math.floor((photo?.dataset.filesize ?? 0) /1000)}KB`"></span>
        <a class = "lightbox__detail btn btn-sm btn-outline-light" :href = "`{{ config.dirs.web.photo }}` + photo?.dataset.originalSrc" target = "_blank">Original {{ icon("bi-box-arrow-up-right") }}</a>
    </div>
</div>

<script src = "{{ url('/public/js/album.js') }}" type="module"></script>

<script defer src="https://unpkg.com/@alpinejs/persist@3.x.x/dist/cdn.min.js"></script>
<script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>