<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% if title is defined %}{{ title }} &lt; {% endif %}Photolib
        </title>
        <link rel = "stylesheet" type="text/css" href="{{ url('/public/css/style.css') }}">
    </head>
    <body>
        <div class = "app">
            <div class="navbar">
                <div class="d-flex">
                    <div class="navbar-brand">
                        <a class="navbar-icon" href = "{{ album(config.rootAlbumId) }}">PL</a>
                        {% if title is defined %}
                            {{ title }}
                        {% endif %}
                    </div>
                    {% if Album is defined %}
                        <div class="d-inline-flex align-items-center gap-1" x-data="{}" :class="$store.sorting && 'invisible'">
                            {% if !Album.isRootAlbum() %}
                                <div class="dropdown dropdown--no-caret">
                                    <button class="btn btn-icon btn-ghost-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                        {{ icon("bi-gear-fill") }}
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a class="dropdown-item" href="#" x-data="albumRename" @click="start('{{Album.name|escape_js}}', {{ Album.id}} )">
                                                {{ icon("bi-input-cursor-text me-2") }}Rename
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" href="#" x-data="albumMove" @click="start()">
                                                {{ icon("bi-folder-symlink me-2") }}Move
                                            </a>
                                        </li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li>
                                            {% if subAlbums|length > 0 OR Album.hasPhotos() %}
                                                <small class="form-text d-block ps-3 lh-sm text-danger">
                                                    This album cannot be deleted because it contains photos and/or albums.
                                                </small>
                                            {% else %}
                                                <a class="dropdown-item text-danger" href="#" x-data="albumDelete" @click="deleteAlbum()">
                                                    {{ icon("bi-trash-fill me-2") }}Delete
                                                </a>
                                            {% endif %}
                                        </li>
                                    </ul>
                                </div>
                            {% endif %}
                            <button class="btn btn-ghost-secondary btn-icon" data-bs-toggle="modal" data-bs-target="#new-album-modal">
                                {{ icon("bi-folder-plus") }}
                            </button>
                        </div>
                    {% endif %}
                </div>
                {% if Album is defined %}
                    <div class="btn-toolbar gap-3" role="toolbar" aria-label="Album-wide tools">
                        <div class="d-flex gap-1" x-data="gridSize">
                            <div class="btn btn-ghost-secondary btn-icon" :class="size == 'sm' && 'active'" @click="setSize('sm')">
                                {{ icon("bi-grid-3x3-gap") }}
                            </div>
                            <div class="btn btn-ghost-secondary btn-icon" :class="size == 'lg' && 'active'" @click="setSize('lg')">
                                {{ icon("bi-grid") }}
                            </div>
                        </div>
                        <div class="d-flex gap-1" x-data="gridRatio">
                            <div class="btn btn-ghost-secondary btn-icon" :class="ratio == 'square' && 'active'" @click="setRatio('square')">
                                {{ icon("bi-aspect-ratio") }}
                            </div>
                            <div class="btn btn-ghost-secondary btn-icon"  :class="ratio == 'natural' && 'active'" @click="setRatio('natural')">
                                {{ icon("bi-square") }}
                            </div>
                        </div>
                    </div>
                {% endif %}
                {% if router.getControllerName() != "battle" %}
                    <div>
                        <a href ="{{ url('/duplicates') }}" class="btn btn-icon btn-ghost-secondary">
                            {{ icon("bi-copy") }}
                        </a>
                        <a href ="{{ url('/battle') }}" class="btn btn-icon btn-ghost-secondary">
                            {{ icon("bi-bar-chart") }}
                        </a>
                    </div>
                {% else %}
                    <a href="#" class="btn btn-ghost-secondary" id="battle-stats">
                        Stats
                    </a>
                {% endif %}
            </div>
            <div class="px-2">
                {{ flash.output() }}
            </div>
            {{ content() }}
            {{ partial("partials/_toastPartial") }}
        </div>
        <script type="text/javascript">
            window.webRootPath = "{{ config.dirs.web.root }}";
            window.rootAlbumId = {{ config.rootAlbumId }};
            window.maxFileSize = {{ config.image.maxFileSize }};
            window.maxResizeDimension = {{ config.image.maxResizeDimension }};
        </script>
        <script src="{{ url('/public/js/toast.js') }}" type="module"></script>
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/image-blob-reduce@4.1.0/dist/image-blob-reduce.min.js" integrity="sha256-xr4fmtp/M9yaevmd5u/KZeWQSiU2lzUlW2iAxKjxOfI=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
        {{ assets.outputJs("footer") }}
    </body>
</html>