<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% if title is defined %}{{ title }} &lt; {% endif %}Photolib
        </title>
        <link rel = "stylesheet" type="text/css" href="{{ url('/public/css/style.css') }}" />
    </head>
    <body>
        <div class = "app">
            <div class="navbar">
                <div class="navbar-brand">
                    <a class="navbar-icon" href = "{{ viewHelper.albumUrl(1) }}">PL</a>
                    {% if title is defined %}
                        {{ title }}
                    {% endif %}
                </div>
                {% if Album is defined %}
                    <div class="btn-toolbar gap-2" role="toolbar" aria-label="Album-wide tools">
                        <div class="btn-group" x-data="gridSize">
                            <div class="btn btn-outline-secondary" :class="size == 'sm' && 'active'" @click="setSize('sm')">
                                {{ viewHelper.icon("bi-grid-3x3-gap") }}
                            </div>
                            <div class="btn btn-outline-secondary" :class="size == 'lg' && 'active'" @click="setSize('lg')">
                                {{ viewHelper.icon("bi-grid") }}
                            </div>
                        </div>
                        <div class="btn-group" x-data="gridRatio">
                            <div class="btn btn-outline-secondary" :class="ratio == 'square' && 'active'" @click="setRatio('square')">
                                {{ viewHelper.icon("bi-aspect-ratio") }}
                            </div>
                            <div class="btn btn-outline-secondary"  :class="ratio == 'natural' && 'active'" @click="setRatio('natural')">
                                {{ viewHelper.icon("bi-square") }}
                            </div>
                        </div>
                    </div>
                {% endif %}
                <a href ="{{ url('/battle') }}" class="btn btn-outline-secondary">
                    {{ viewHelper.icon("bi-bar-chart") }}
                </a>
            </div>
            <?= $this->getContent(); ?>
        </div>
        <script src = "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src = "{{ url('/public/js/site.js') }}" type="module"></script>
    </body>
</html>